{
  "openapi": "3.0.0",
  "info": {
    "title": "Rastreabilidade de Embalagens Retornáveis",
    "description": "Sistema de monitoramento e controle de embalagens",
    "version": "2.0.0"
  },
  "servers": [
    {
      "url": "http://localhost:7400/api/",
      "description": "Base de testes"
    }
  ],
  "paths": {
    "/model": {
      "get": {
        "tags": ["models"],
        "security": [{ "bearerAuth": [] }],
        "summary": "Listar modelos",
        "description": "Lista todos os modelos cadastrados no banco de dados",
        "responses": {
          "200": {
            "description": "Sucesso: Retorna a lista de todos os modelos cadastrados"
          },
          "401": {
            "description": "Não autorizado"
          },
          "500": {
            "description": "Falha: Rota finalizada"
          }
        }
      }
    },
    "/user": {
      "get": {
        "tags": ["users"],
        "security": [{ "bearerAuth": [] }],
        "summary": "Listar usuários",
        "description": "Lista todos os usuários ativos cadastrados no banco",
        "parameters": [
          {
            "name": "take",
            "in": "query",
            "description": "quantidade de resultados a serem retornados"
          },
          {
            "name": "skip",
            "in": "query",
            "description": "quantidade de resultados a serem pulados"
          } 
        ],
        "responses": {
          "200": {
            "description": "Sucesso: Retorna a lista de todos os usuário ativos"
          },
          "401": {
            "description": "Não autorizado"
          },
          "500": {
            "description": "Falha: Finaliza a rota"
          }
        }
      },
      "post": {
        "tags": ["users"],
        "security": [{ "bearerAuth": [] }],
        "summary": "Criar usuário",
        "description": "Recebe os dados da requisição e valida o email e matricula para criar um novo usuário",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/RequestCreateUser"
              },
              "examples": {
                "RequestUserAdmin": {
                  "value": {
                    "nome": "admin",
                    "matricula": "9999999",
                    "email": "admin@tuti.com",
                    "password": "tuti@123",
                    "admin": true,
                    "mnt": false
                  }
                },
                "RequestUserMnt": {
                  "value": {
                    "nome": "mnt",
                    "matricula": "88888888",
                    "email": "mnt@tuti.com",
                    "password": "tuti@123",
                    "admin": false,
                    "mnt": true
                  }
                },
                "RequestUserStandard": {
                  "value": {
                    "nome": "standard",
                    "matricula": "0000001",
                    "email": "standard@tuti.com",
                    "password": "tuti@123",
                    "admin": false,
                    "mnt": false
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Sucesso: Retorna usuário criado"
          },
          "400": {
            "description": "Falha: Retorna o erro de dados inválidos"
          },

          "404": {
            "description": "Falha: Retorna o erro de recursos nao encontrados"
          },

          "401": {
            "description": "Não autorizado"
          },
          "500": {
            "description": "Falha: Rota finalizada"
          }
        }
      }
    },

    "/users/{id}": {
      "get": {
        "tags": ["users"],
        "security": [{ "bearerAuth": [] }],
        "summary": "Buscar usuário",
        "description": "Recebe uma id pro parametro e retorna um usuário no banco",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "usuário buscado pelo id",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Sucesso: Retorna o usuário"
          },
          "401": {
            "description": "Não autorizado"
          },
          "404": {
            "description": "Parametro inválido"
          },
          "500": {
            "description": "Falha: finaliza a rota"
          }
        }
      },
      "put": {
        "tags": ["users"],
        "security": [{ "bearerAuth": [] }],
        "summary": "Editar usuário",
        "description": "Recebe uma id por parâmetro e edita seus dados ",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "id de usuário que será alterado",
            "required": true
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/RequestEditUser"
              },
              "examples": {
                "RequestUserAdmin": {
                  "value": {
                    "nome": "NovoNome",
                    "matricula": "9999999",
                    "email": "novoEmail@tuti.com",
                    "password": "novasenha",
                    "admin": true,
                    "mnt": false,
                    "ativo": true
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Sucesso: Retorna o usuário editado"
          },
          "400": {
            "description": "Falha: Finaliza a rota"
          },
          "401": {
            "description": "Não autorizado"
          },
          "500": {
            "description": "Falha: Rota finalizada"
          }
        }
      },
      "delete": {
        "tags": ["users"],
        "security": [{ "bearerAuth": [] }],
        "summary": "Deletar usuário",
        "description": "Recebe um id por parâmetro, busca o usuário e apaga ele do sistema",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "Id do usuário que será apagado",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Sucesso: Usuário deletado"
          },
          "401": {
            "description": "Não autorizado"
          },
          "500": {
            "description": "Falha: Rota finalizada"
          }
        }
      }
    }

  },
  "components": {
    "schemas": {
      "RequestCreateUser": {
        "type": "object",
        "properties": {
          "nome": { "type": "string" },
          "matricula": { "type": "string" },
          "email": { "type": "string" },
          "password": { "type": "string" },
          "admin": { "type": "boolean" },
          "mnt": { "type": "boolean" }
        }
      },
      "RequestEditUser": {
        "type": "object",
        "properties": {
          "nome": { "type": "string" },
          "matricula": { "type": "string" },
          "email": { "type": "string" },
          "password": { "type": "string" },
          "admin": { "type": "boolean" },
          "mnt": { "type": "boolean" },
          "ativo": { "type": "boolean" }
        }
      },
      "RequestSessionUser": {
        "type": "object",
        "properties": {
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          }
        }
      },
      "RequestCreateCustomer": {
        "type": "object",
        "properties": {
          "file": {
            "type": "string",
            "format": "binary",
            "description": "Selecionar imagem do cliente"
          },
          "cnpj": { "type": "string", "description": "Necessário cnpj válido" },
          "razao_social": { "type": "string" }
        }
      },
      "RequestEditCustomer": {
        "type": "object",
        "properties": {
          "file": {
            "type": "string",
            "format": "binary",
            "description": "Selecionar nova imagem do cliente ou enviar vázio para não alterar a imagem"
          },
          "cnpj": {
            "type": "string",
            "description": "Necessário cnpj válido"
          },
          "razao_social": { "type": "string" }
        }
      },
      "RequestCreateModel": {
        "type": "object",
        "properties": {
          "file": {
            "type": "string",
            "format": "binary",
            "description": "Selecionar imagem do modelo"
          },
          "descricao": {
            "type": "string"
          }
        }
      },
      "RequestEditModel": {
        "type": "object",
        "properties": {
          "file": {
            "type": "string",
            "format": "binary",
            "description": "Selecionar uma nova imagem do modelo ou vázio"
          },
          "descricao": {
            "type": "string"
          }
        }
      },
      "RequestCreatePackage": {
        "type": "object",
        "properties": {
          "serial_number": {
            "type": "string"
          },
          "origem": {
            "type": "string"
          },
          "FK_modelo": {
            "type": "string"
          }
        }
      },
      "RequestEditPackage": {
        "type": "object",
        "properties": {
          "serial_number": { "type": "string" },
          "FK_destino": { "type": "string" },
          "FK_modelo": { "type": "string" },
          "origem": { "type": "string" },
          "status": { "type": "number" }
        }
      },
      "RequestCreateProvider": {
        "type": "object",
        "properties": {
          "nome": {
            "type": "string"
          },
          "externo": {
            "type": "boolean"
          }
        }
      },
      "RequestCreateCpc": {
        "type": "object",
        "properties": {
          "FK_customer": {
            "type": "string"
          },
          "FK_model": {
            "type": "string"
          }
        }
      },
      "RequestEditCpc": {
        "type": "object",
        "properties": {
          "FK_customer": {
            "type": "string"
          },
          "FK_model": {
            "type": "string"
          }
        }
      },
      "RequestCreateSme": {
        "type": "object",
        "propertieis": {
          "id_customer": { "type": "string" },
          "id_package": { "type": "string" },
          "status": { "type": "number" },
          "matricula": { "type": "string" },
          "username": { "type": "string" }
        }
      },
      "RequestCreateSmm": {
        "type": "object",
        "properties": {
          "user": {
            "type": "object",
            "properties": {
              "username": {
                "type": "string"
              },
              "matricula": {
                "type": "string"
              }
            }
          },
          "fornecedor": {
            "type": "object",
            "properties": {
              "descricao": {
                "type": "string"
              },
              "statusDoFornecedor": {
                "type": "boolean"
              }
            }
          },
          "embalagem": {
            "type": "object",
            "properties": {
              "descricao": {
                "type": "string"
              },
              "serial_number": {
                "type": "string"
              },
              "modeloDaEmbalagem": {
                "type": "string"
              }
            }
          }
        }
      }
    },
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  }
}
